name: 'check-conventional-commits'
description: 'Checks if all the commits (of the branch which triggered the event) comply to the conventional commits standard'
author: Alex Speranza

inputs:
  token:
    description: 'Personal access token with pull permissions on repository'
    required: true

outputs:
  errors:
    description: 'Number of non conventional commit messages'
    value: ${{ steps.run-script.outputs.errors }}

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4.1.1
      with:
        fetch-depth: 0
        token: ${{ inputs.token }}
    - id: run-script
      run: >
        test "$(./script.sh)" -eq "0"
      shell: bash

